kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# 컨트롤 플레인
- role: control-plane
  extraPortMappings:
  # DevSecOps 웹 서비스 포트
  # - 외부에서 웹 애플리케이션 접근용
  # - 호스트 접근: http://localhost:30080
  - containerPort: 30080
    hostPort: 30080
    listenAddress: "0.0.0.0"
    protocol: TCP

  # Jenkins 웹 인터페이스 포트
  # - CI/CD 파이프라인 관리 웹 UI
  # - 빌드 및 배포 모니터링
  # - 호스트 접근: http://localhost:8080
  - containerPort: 30800
    hostPort: 8080
    listenAddress: "0.0.0.0"
    protocol: TCP

  # Jenkins JNLP 에이전트 포트
  # - Jenkins 워커 노드 연결
  # - 분산 빌드 에이전트 통신
  # - 호스트 접근: localhost:50000
  - containerPort: 30850
    hostPort: 50000
    listenAddress: "0.0.0.0"
    protocol: TCP

# SonarQube 웹 인터페이스 포트
  # - 코드 품질 분석 웹 UI
  # - 호스트 접근: http://localhost:30900
  - containerPort: 30900
    hostPort: 30900
    listenAddress: "0.0.0.0"
    protocol: TCP

# 워커 노드 1: 웹서버
- role: worker
  labels:
    node-type: webserver
    purpose: apache-php

# 워커 노드 2: Jenkins
- role: worker
  labels:
    node-type: jenkins
    purpose: jenkins

# 워커 노드 3: 백업 DB
- role: worker
  labels:
    node-type: backup-db
    purpose: backup-storage

# 워커 노드 5: 로그 DB
- role: worker
  labels:
    node-type: log-db
    purpose: log-storage

# 워커 노드 6: 웹 DB
- role: worker
  labels:
    node-type: web-db
    purpose: mariadb-we